name: bymarkone.com
markdown: kramdown
highlighter: true
relative_permalinks: true
permalink:     pretty
dl: pt
kramdown:
  input: GFM
locales:
  en:
    new-testament: "New Testament"
    gospels: "Gospels"
    books-matthew: "Matthew"
    books-mark: "Mark"
    books-luke: "Luke"
    books-john: "John"
    books-acts: "Acts"
    books-romans: "Romans"
    books-first-corinthians: "1 Corinthians"
    books-second-corinthians: "2 Corinthians"
    books-galatians: "Galatians"
    books-ephesians: "Ephesians"
    books-philippians: "Philippians"
    books-colossians: "Colossians"
    books-first-tessalonians: "1 Tessalonians"
    books-second-tessalonians: "2 Tessalonians"
    books-philemon: "Philemon"
    books-first-timothy: "1 Timothy"
    books-second-timothy: "2 Timothy"
    books-titus: "Titus"
    books-hebrews: "Hebrews"
    books-james: "James"
    books-first-peter: "1 Peter"
    books-second-peter: "2 Peter"
    books-first-john: "1 John"
    books-second-john: "2 John"
    books-third-john: "3 John"
    books-jude: "Jude"
    books-revelation: "Revelation"
    
  pt:
    new-testament: "Novo Testamento"
    gospels: "Evangelhos"
    books-matthew: "Mateus"
    books-mark: "Marcos"
    books-luke: "Lucas"
    books-john: "João"
    books-acts: "Atos"
    books-romans: "Romanos"
    books-first-corinthians: "1 Coríntios"
    books-second-corinthians: "2 Coríntios"
    books-galatians: "Gálatas"
    books-ephesians: "Efésios"
    books-philippians: "Filipenses"
    books-colossians: "Colossenses"
    books-first-tessalonians: "1 Tessalonicenses"
    books-second-tessalonians: "1 Tessalonicenses"
    books-philemon: "Filemon"
    books-first-timothy: "1 Timóteo"
    books-second-timothy: "2 Timóteo"
    books-titus: "Tito"
    books-hebrews: "Hebreus"
    books-james: "Tiago"
    books-first-peter: "1 Pedro"
    books-second-peter: "2 Pedro"
    books-first-john: "1 João"
    books-second-john: "2 João"
    books-third-john: "3 João"
    books-jude: "Judas"
    books-revelation: "Apocalipse"
